Practical Machine Learning Course Project
=========================================

Abstract
--------
Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement - a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset). 
Random forest method used

Read Dataset
------------

```{r read}
pmlTraining <- read.csv("pml-training.csv", header = TRUE, na.strings = c("NA",""))
pmlTesting <- read.csv("pml-testing.csv", header = TRUE, na.strings = c("NA",""))
training       <- pmlTraining[,-c(1,5,6)]
test           <- pmlTesting[,-c(1,5,6)]
```

Analysis
--------

Split training set into secondary training set and test set

```{r split, message=FALSE}
library(caret)
trainingIndex  <- createDataPartition(training$classe, p=.50, list=FALSE)
training.train <- training[ trainingIndex,]
training.test  <- training[-trainingIndex,]
```

Next we create a function to remove entire NA columns, and apply it to both data frames. Lastly we create a function that removes any variables with missing NAs and apply this to the training set.
```{r nacols}
rm.na.cols     <- function(x) { x[ , colSums( is.na(x) ) < nrow(x) ] }
training.train <- rm.na.cols(training.train)
training.test  <- rm.na.cols(training.test)
complete       <- function(x) {x[,sapply(x, function(y) !any(is.na(y)))] }
incompl        <- function(x) {names( x[,sapply(x, function(y) any(is.na(y)))] ) }
trtr.na.var    <- incompl(training.train)
trts.na.var    <- incompl(training.test)
training.train <- complete(training.train)
training.test  <- complete(training.test)
```

Method
------

Use Random Forests method by applying bagging to tree learners.

```{r train, cache=TRUE}
library(randomForest)
random.forest <- train(training.train[,-57],
                       training.train$classe,
                       tuneGrid=data.frame(mtry=3),
                       trControl=trainControl(method="none")
                       )
```

Results
-------

```{r summary}
summary(random.forest)
```

Prediction Results vs Actual Data
```{r confusion_matrix}
confusionMatrix(predict(random.forest,
                        newdata=training.test[,-57]),
                training.test$classe
                )
```
Kappa statistic of 0.994 reflects the out-of-sample error.

```{r plot}
plot( varImp(random.forest) )
```